### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by mathieu-ferry** [metayoub/Qoldy_avatarGroup#1]
* What is the expected datasource format?
* When setting 6 or 9 max avatars to display, only 3 are displayed in the Page editor canvas
* Entity selections should be supported

**Comment by metayoub** [comment]
What is the expected datasource format?
The component should be linked to an Selection.

When setting 6 or 9 max avatars to display, only 3 are displayed in the Page editor canvas.
Maybe we should fix the default to 10 instead of 3

Entity selections should be supported.
it already supported.

**Comment by mathieu-ferry** [comment]
OK but documentation does not indicate any of this: I had to check the component code to see that the component displays the attributes from the datasource: either "name" or "image". I first tried with a collection, would it work?

**Comment by metayoub** [comment]
we did update the readMe to be more helpful
